### ISSUE TITLE
Security of personal access token

### ISSUE THREAD

**Issue by khromov** [matootie/github-docker#3]
Hello, in the documentation example, you don't suggest using GitHub secrets:

```
...
# GitHub Personal Access Token for the user.
personalAccessToken: 
...
```

If would be better if you suggested to use a secret:

```
# GitHub Personal Access Token for the user. Add the token in Repo settings > Secrets
personalAccessToken: ${{ secrets.ACCESS_TOKEN }}
```

On another note, as I'm building using this action I get the following in my build log:

```
docker login docker.pkg.github.com --username khromov --password ***
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
```

Does this pose a risk for my token, in a way that someone else could get a hold of it?

**Comment by matootie** [comment]
Hello @khromov, thank you for contributing!

When GitHub provides you with sample code to use an Action from the Marketplace, the snippet is automatically generated from the corresponding `action.yml` file. For example, in the `action.yml` file for **github-docker**:

```yaml
inputs:
  personalAccessToken:
    description: 'GitHub Personal Access Token for the user.'
    required: true
```

I can not provide a default value of `${{ secrets.PERSONAL_ACCESS_TOKEN }}`, but I have put this example [in the README](https://github.com/matootie/github-docker#example-usage) in the hopes that it will be clear to users that this is the intended method. To further this, I'm going to a suggest the use of a GitHub Secret, in the description field for the `personalAccessToken` input, like so:

```yaml
inputs:
  personalAccessToken:
    description: 'GitHub Personal Access Token for the user. Consider using a GitHub Secret.'
    required: true
```

_As for your concerns with your token being stored unencrypted on the worker machine_; GitHub actions workers run in virtual machines, and as far as I know this means that any files that were not cached or archived during the workflow will be removed. **This isn't exactly that reassuring**, which is why I'm going see if I can configure the action to use a [Credential Store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) with Docker. Until then, I'll also have the action itself delete the docker `config.json` after the image is pushed, so that it will be gone and unavailable to other actions for the remainder of the job cycle.

**Comment by matootie** [comment]
I've implemented the temporary *"solution"* while I look into a better way to secure the credentials.

https://github.com/matootie/github-docker/commit/3dff630760df5f10e41f0b87bdfb87f1c6cb71e2/checks?check_suite_id=377135613#step:3:95

With this change, the token is only stored in plain text during the lifespan of **this action**. Before the action runs, the token can not be found locally, and because it's deleted at the end, it also can not be found after.

Of course, if you use a token from your secrets, there is absolutely no way that it will appear in logs as GitHub masks anything found in your secrets.

**Comment by tommywalkie** [comment]
@khromov While @matootie 's recent change is a good step in the right direction, if you need to do _whatever business logic CI job_ that needs whatever credentials stored in Github Secrets and you are really concerned about CI stuff security, that usually means that you are intending to collaborate with some people on a project.

One could easily edit Github Actions config file and replace `matootie/github-docker` use with a plain command `docker login docker.pkg.github.com --username username --password ${{ secrets.ACCESS_TOKEN }}` and skip every future steps and security layers.

The real thing you need to protect, in my opinion, is the CI config.

I think there are several choices possible without asking @matootie to do anything :
- **_The lazy one_** : Be the only member of your project.
- **_The simple and efficient one_** : Adopt [a Git forking flow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) in your project and require contributors to fork the project and make PRs, without forgetting to add some condition in jobs `if: ${{ github.repo == 'your-actual-repo' }}` so any Github Actions triggered in forks won't fail because Github Secrets weren't configured on their side.
- **_The fancy one_** : Make your _whatever business logic CI job_ external, create another repo on Gitlab or Github and bring the _whatever business logic CI job_ there, and trigger the external job from your actual development repo using [Triggers API](https://docs.gitlab.com/ee/ci/triggers/) (for Gitlab) or [repository dispatch events](https://developer.github.com/v3/repos/#create-a-repository-dispatch-event) (for Github) via a one-line cURL command that will be stored in Github Secrets. May be a useful workflow in case you're working on a multi-repo project and/or if you like separating concerns.

**Comment by matootie** [comment]
Thanks for the input @tommywalkie

**Comment by khromov** [comment]
Thank you for the help and continued improvements!

As a further security improvement, do you know if there is any way to restrict the use of a Personal Access Token to a specific repository? (Other than creating a secondary account with more limited access) The way I understand it, right now, it takes only one malicious GitHub action (that steals Personal Access Tokens) to bring down an entire GitHub account, because a PAT is valid for every repo the account has access to.

**Comment by matootie** [comment]
You're able to use the access token provided to you by the repository, *for* the repository.

It's an integrated secret that you can't edit or see by default, but it's there. I've outlined that usage in the latest release of GitHub Docker.

```yaml
- name: Publish Image
  uses: matootie/github-docker@v2.0.0
  with:
    accessToken: ${{ secrets.GITHUB_TOKEN }}
```

The `GITHUB_TOKEN` secret is valid **only** for the given repository.

**Comment by tommywalkie** [comment]
@matootie I think @khromov is talking about the actual **Github Developer Token** that you usually find and create in account settings and then hide it behind a repository secret, this is the thing needed to perform Git or Github Docker Registry operations like in `matootie/github-docker`, hence why he's worried about if the token is used once by a malicious contributor, the whole Github account can be messed up, **even the private repos** if he's smart enough ([API REST /user/list source](https://developer.github.com/v3/repos/#list-your-repositories)). From the same exact Github Action, once he understand he _has_ the Github Developer Token, the malicious contributor can potentially do : 
```bash
git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/khromov/some-public-repo.git
# do some stuff
git push
# find unknown khromov's private repos
curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/list?visibility=private
# then who knows...
```
This is why, in my opinion, I think any Github Developer Token should be used from the outside only, hence why i was suggesting for using an external repo that acts like a centralized CI/CD platform where only the CI/CD nerd is allowed in. 😁

**Comment by khromov** [comment]
@matootie Sorry for causing the confusion in this ticket and for not reading up. As you say the `GITHUB_TOKEN` secret is automatically available [as per the documentation](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token) and it's also [limited to the current repo](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token).

It also says the token expires after 60 minutes, so I'm again sorry for taking up time and thank you for your amazing responses (and for this amazing GitHub Action!)
